package:
  name: ccpi-apps
  version: {{ environ['CIL_VERSION'] }}


build:
  preserve_egg_dir: False
  script_env:
    - CIL_VERSION   
#  number: 0
  
  entry_points:
    - CILViewerLaunch = ccpi.apps.standaloneQT:main

requirements:
  build:
    - python
    - numpy x.x
    - setuptools
    - cython
    - vtk
    - vc 14 # [win and py36] 
    - vc 14 # [win and py35] 
    - vc 9  # [win and py27]
    - cmake 

  run:
    - python
    - numpy x.x
    - ccpi-viewer =={{ environ['CIL_VERSION'] }}
    - vc 14 # [win and py36]
    - vc 14 # [win and py35] 
    - vc 9  # [win and py27]
    - pyqt ==5.6.0
    - natsort
	
about:
  home: http://www.ccpi.ac.uk
  license:  BSD license
  summary: 'CCPi Core Imaging Library Quantification Toolbox'
